"""Trade attachments: storage, refusals, and the endpoints that expose them.

    cd backend && python -m pytest tests -q

Screenshots and statements are attached to a single trade's review. The points
worth pinning:

  * the file that lands on disk is named by us, not by the upload — a name is
    caller-controlled and must not be able to traverse out of the uploads dir;
  * the allowlist is refused rather than blocklisted, so an unknown executable
    suffix is rejected without a code change;
  * deleting a trade takes its files with it, and deleting an attachment takes
    both the row and the file;
  * the whole feature survives `init_db()` on a database that predates it.
"""
import sqlite3
import sys
from pathlib import Path

import pytest

BACKEND = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND))

import attachments  # noqa: E402


@pytest.fixture
def client(tmp_path, monkeypatch):
    """An app on a scratch database with its own uploads directory.

    The trade group key is generated by the server (it embeds the entry time),
    so it is taken from the create response rather than spelled out here.
    """
    db = tmp_path / "journal.db"
    uploads = tmp_path / "uploads"
    uploads.mkdir()
    monkeypatch.setenv("DATABASE_PATH", str(db))
    monkeypatch.setenv("UPLOAD_DIR", str(uploads))
    for name in ("database", "main"):
        sys.modules.pop(name, None)
    import database
    database.DB_PATH = str(db)
    import main
    main.UPLOAD_DIR = str(uploads)
    from fastapi.testclient import TestClient
    with TestClient(main.app) as c:
        c.db = str(db)
        c.uploads = str(uploads)

        def make_trade(ticker, date, time):
            r = c.post("/api/trades", json={
                "account_id": 1, "date": date, "ticker": ticker,
                "instrument_type": "STOCK", "side": "LONG",
                "entry_price": 366.09, "quantity": 100, "time": time,
            })
            assert r.status_code == 201, r.text
            return r.json()

        c.post("/api/accounts", json={"name": "Test", "type": "day_trading"})
        first = make_trade("TSLA", "2026-09-10", "09:54:10")
        second = make_trade("META", "2026-09-11", "09:54:10")
        c.group = first["trade_group"]
        c.other_group = second["trade_group"]
        c.trade_id = first["id"]
        yield c


def upload(client, group=None, name="chart.png", content=b"\x89PNG-fake",
           ctype="image/png"):
    return client.post(f"/api/trades/{group or client.group}/attachments",
                       files={"file": (name, content, ctype)})


def stored_path(uploads, name):
    """Where attachment_path puts a file: the subdir the static mount ignores."""
    return Path(uploads, attachments.SUBDIR, name)


def stored_files(uploads):
    d = Path(uploads, attachments.SUBDIR)
    return [p.name for p in d.iterdir()] if d.is_dir() else []


def upload_unchecked(client, group=None, name="chart.png",
                     content=b"\x89PNG-fake", ctype="image/png"):
    """Upload without asserting, so a refusal can be inspected."""
    return upload(client, group=group, name=name, content=content, ctype=ctype)


def test_a_file_is_stored_and_listed(client):
    r = upload(client)
    assert r.status_code == 201, r.text
    meta = r.json()
    assert meta["original_name"] == "chart.png"
    assert meta["kind"] == "image"
    assert meta["size_bytes"] == len(b"\x89PNG-fake")

    listed = client.get(f"/api/trades/{client.group}/attachments").json()
    assert [a["id"] for a in listed["attachments"]] == [meta["id"]]


def test_the_stored_name_is_generated_not_taken_from_the_upload(client):
    """A filename is user-controlled: it must not reach the filesystem."""
    r = upload(client, name="chart.png")
    stored = r.json()["stored_name"]
    assert stored != "chart.png"
    assert stored.endswith(".png")
    assert stored_path(client.uploads, stored).is_file()
    # Only one file, under the uploads dir, named by us.
    assert stored_files(client.uploads) == [stored]


def test_traversal_in_the_filename_never_reaches_the_filesystem(client):
    r = upload(client, name="../../etc/passwd.png")
    assert r.status_code == 201, r.text
    stored = r.json()["stored_name"]
    assert ".." not in stored and "/" not in stored
    assert stored_path(client.uploads, stored).is_file()
    assert not Path(client.uploads).parent.joinpath("etc").exists()


def test_an_unlisted_extension_is_refused(client):
    """Allowlist, not blocklist: an unknown suffix is rejected outright."""
    r = upload_unchecked(client, name="payload.exe", content=b"MZ")
    assert r.status_code == 400
    assert "cannot be attached" in r.json()["error"]
    # Nothing written, no row recorded.
    assert stored_files(client.uploads) == []
    assert client.get(f"/api/trades/{client.group}/attachments").json()["attachments"] == []


def test_a_script_is_refused_too(client):
    for name in ("note.sh", "run.py", "evil.html"):
        r = upload_unchecked(client, name=name, content=b"#!/bin/sh")
        assert r.status_code == 400, f"{name}: {r.json()}"
    assert stored_files(client.uploads) == []


def test_a_file_over_the_limit_is_refused_and_not_written(client):
    big = b"0" * (attachments.MAX_ATTACHMENT_BYTES + 1)
    r = upload_unchecked(client, name="huge.csv", content=big, ctype="text/csv")
    assert r.status_code == 400
    assert "limited to" in r.json()["error"]
    # The cap is checked before the write, so no partial file appears.
    assert stored_files(client.uploads) == []


def test_a_file_at_the_limit_is_accepted(client):
    exact = b"0" * attachments.MAX_ATTACHMENT_BYTES
    r = upload_unchecked(client, name="edge.csv", content=exact, ctype="text/csv")
    assert r.status_code == 201, r.text


def test_an_empty_file_is_refused(client):
    r = upload_unchecked(client, name="empty.txt", content=b"")
    assert r.status_code == 400
    assert "empty" in r.json()["error"]


def test_a_pasted_blob_with_no_filename_still_works(tmp_path):
    """A screenshot pasted from the clipboard can arrive without a name.

    Multipart turns a part with no filename into a plain form field, so the
    HTTP layer can't represent "no name at all" — the UI supplies one. The
    store still refuses to blow up if a caller has nothing, because `or`
    defaults rather than indexing into None.
    """
    uploads = tmp_path / "uploads"
    uploads.mkdir()
    conn = sqlite3.connect(tmp_path / "t.db")
    conn.row_factory = sqlite3.Row
    conn.execute("""CREATE TABLE trade_attachments (
        id INTEGER PRIMARY KEY AUTOINCREMENT, trade_group TEXT NOT NULL,
        original_name TEXT NOT NULL, stored_name TEXT NOT NULL UNIQUE,
        content_type TEXT NOT NULL DEFAULT 'application/octet-stream',
        size_bytes INTEGER NOT NULL,
        created_at TEXT NOT NULL DEFAULT (datetime('now')))""")

    meta = attachments.save(conn, upload_dir=str(uploads), trade_group="g",
                            filename=None, content_type="image/png",
                            raw=b"\x89PNG-pasted")
    assert meta["stored_name"].endswith(".png")
    assert stored_path(uploads, meta["stored_name"]).is_file()
    assert meta["original_name"]


def test_two_uploads_of_the_same_name_do_not_collide(client):
    a = upload(client, name="chart.png", content=b"one").json()
    b = upload(client, name="chart.png", content=b"two").json()
    assert a["stored_name"] != b["stored_name"]
    assert stored_path(client.uploads, a["stored_name"]).read_bytes() == b"one"
    assert stored_path(client.uploads, b["stored_name"]).read_bytes() == b"two"
    assert len(client.get(f"/api/trades/{client.group}/attachments").json()["attachments"]) == 2


def test_download_returns_the_original_bytes_and_name(client):
    payload = b"date,ticker,pnl\n2026-09-10,TSLA,195\n"
    meta = upload(client, name="fills.csv", content=payload, ctype="text/csv").json()
    r = client.get(f"/api/attachments/{meta['id']}/download")
    assert r.status_code == 200
    assert r.content == payload
    assert "fills.csv" in r.headers.get("content-disposition", "")


def test_a_previewable_attachment_comes_back_inline_when_asked(client):
    """Images, PDF and text render in the panel; anything else downloads."""
    for name, ctype in [("shot.png", "image/png"),
                        ("doc.pdf", "application/pdf"),
                        ("notes.txt", "text/plain"),
                        ("fills.csv", "text/csv")]:
        meta = upload(client, name=name, content=b"body", ctype=ctype).json()
        assert meta["previewable"] is True, name

        r = client.get(f"/api/attachments/{meta['id']}/download", params={"inline": "true"})
        assert r.status_code == 200, name
        assert r.headers.get("content-disposition", "").startswith("inline"), name
        assert r.headers["content-type"].startswith(ctype.split("/")[0]), name

    # Text is rendered in a sandboxed iframe by the client; the server pins the
    # same constraint, so a CSV that starts with markup still cannot execute.
    notes = upload(client, name="notes.txt", content=b"<script>x</script>",
                   ctype="text/plain").json()
    r = client.get(f"/api/attachments/{notes['id']}/download", params={"inline": "true"})
    assert "sandbox" in r.headers.get("content-security-policy", "")
    # Non-text inline responses are sniffable only as their own type.
    png = upload(client, name="shot2.png", content=b"\x89PNG").json()
    r = client.get(f"/api/attachments/{png['id']}/download", params={"inline": "true"})
    assert "nosniff" in r.headers.get("x-content-type-options", "")


def test_an_office_or_heic_attachment_is_never_served_inline(client):
    """The inline flag is a hint, not a licence: non-renderable files download."""
    for name, ctype in [("book.xlsx",
                         "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
                        ("letter.doc", "application/msword"),
                        ("photo.heic", "image/heic")]:
        meta = upload(client, name=name, content=b"BLOB", ctype=ctype).json()
        assert meta["previewable"] is False, name

        r = client.get(f"/api/attachments/{meta['id']}/download", params={"inline": "true"})
        assert r.status_code == 200, name
        assert r.headers.get("content-disposition", "").startswith("attachment"), name


def test_without_the_inline_flag_the_download_still_triggers_the_save_dialog(client):
    """The flag must not have changed what a plain download does."""
    meta = upload(client, name="shot.png", content=b"\x89PNG").json()
    r = client.get(f"/api/attachments/{meta['id']}/download")
    assert r.headers.get("content-disposition", "").startswith("attachment")
    # The source URL used as an <img> src still asks for inline; a preview box
    # and a download link are the same bytes with different instructions.
    r2 = client.get(f"/api/attachments/{meta['id']}/download", params={"inline": "1"})
    assert r2.headers.get("content-disposition", "").startswith("inline")


def test_the_static_uploads_mount_cannot_serve_an_attachment(client):
    """Only the download route may hand these bytes out.

    UPLOAD_DIR is mounted read-only-ish at `/uploads` for diary screenshots, so
    anything left in the directory's top level is fetchable by name from any
    local origin. Attachments are private to one trade, so they are stored in a
    subdirectory the mount does not reach; this would return 200 with the raw
    bytes if they were written to the top level.
    """
    meta = upload(client, name="secret-note.png", content=b"SENSITIVE").json()
    r = client.get(f"/uploads/{meta['stored_name']}")
    assert r.status_code == 404, "attachment bytes are reachable at /uploads"
    assert b"SENSITIVE" not in r.content
    # ...and still come back correctly through the guarded route.
    assert client.get(f"/api/attachments/{meta['id']}/download").content == b"SENSITIVE"
    # The mount itself must stay usable: diary screenshots depend on it.
    Path(client.uploads, "diary.png").write_bytes(b"DIARY")
    assert client.get("/uploads/diary.png").content == b"DIARY"


def test_delete_removes_row_and_file(client):
    meta = upload(client, name="chart.png").json()
    path = stored_path(client.uploads, meta["stored_name"])
    assert path.is_file()

    assert client.delete(f"/api/attachments/{meta['id']}").status_code == 200
    assert not path.exists()
    assert client.get(f"/api/trades/{client.group}/attachments").json()["attachments"] == []


def test_delete_of_a_missing_attachment_is_404(client):
    assert client.delete("/api/attachments/999999").status_code == 404


def test_a_unknown_trade_gets_404_not_an_empty_list(client):
    r = client.get("/api/trades/does_not_exist/attachments")
    assert r.status_code == 404
    assert upload_unchecked(client, group="does_not_exist").status_code == 404
    assert stored_files(client.uploads) == []


def test_deleting_a_trade_removes_its_files(client):
    meta = upload(client, name="chart.png").json()
    path = stored_path(client.uploads, meta["stored_name"])
    trade_id = client.trade_id

    assert client.delete(f"/api/trades/{trade_id}").status_code == 200
    assert not path.exists()
    assert client.get(f"/api/trades/{client.group}/attachments").status_code == 404


def test_other_trades_keep_their_files_when_one_is_deleted(client):
    mine = upload(client, name="mine.png").json()
    theirs = upload(client, group=client.other_group, name="theirs.png").json()
    trade_id = client.trade_id

    client.delete(f"/api/trades/{trade_id}")

    assert stored_path(client.uploads, theirs["stored_name"]).is_file()
    assert not stored_path(client.uploads, mine["stored_name"]).exists()
    assert [a["id"] for a in
            client.get(f"/api/trades/{client.other_group}/attachments").json()["attachments"]] == [theirs["id"]]


def test_a_tampered_row_cannot_point_the_download_outside_uploads(client, tmp_path):
    """Rows are data, not paths: a stored_name of '../../x' must not read it."""
    secret = tmp_path / "secret.env"
    secret.write_text("API_KEY=nope")
    meta = upload(client, name="chart.png").json()

    conn = sqlite3.connect(client.db)
    conn.execute("UPDATE trade_attachments SET stored_name='../../secret.env' WHERE id=?",
                 (meta["id"],))
    conn.commit()
    conn.close()

    r = client.get(f"/api/attachments/{meta['id']}/download")
    assert r.status_code == 404
    assert "missing" in r.json()["error"]
    assert b"API_KEY" not in r.content


def test_a_tampered_row_with_an_absolute_path_is_refused(client):
    meta = upload(client, name="chart.png").json()
    conn = sqlite3.connect(client.db)
    conn.execute("UPDATE trade_attachments SET stored_name='/etc/passwd' WHERE id=?",
                 (meta["id"],))
    conn.commit()
    conn.close()
    assert client.get(f"/api/attachments/{meta['id']}/download").status_code == 404


def test_init_db_repairs_early_account_scoped_attachment_table_without_losing_rows(client):
    """Converge the earlier NOT NULL account_id draft and preserve metadata."""
    import database

    db = client.db
    stored = upload(client, name="keep-me.png", content=b"retained").json()
    conn = sqlite3.connect(db)
    conn.execute("ALTER TABLE trade_attachments ADD COLUMN account_id INTEGER NOT NULL DEFAULT 1")
    conn.commit()
    conn.close()

    database.DB_PATH = db
    database.init_db()
    database.init_db()  # repair and ordinary init must both be repeatable

    conn = sqlite3.connect(db)
    conn.row_factory = sqlite3.Row
    cols = [r["name"] for r in conn.execute("PRAGMA table_info(trade_attachments)")]
    row = conn.execute("SELECT * FROM trade_attachments WHERE id=?", (stored["id"],)).fetchone()
    conn.close()

    assert "account_id" not in cols
    assert row["stored_name"] == stored["stored_name"]
    assert row["original_name"] == "keep-me.png"
    assert stored_path(client.uploads, stored["stored_name"]).read_bytes() == b"retained"

    # Fresh inserts match the live pre-fix failure mode and no longer require an account_id.
    conn = sqlite3.connect(db)
    conn.row_factory = sqlite3.Row
    meta = attachments.save(conn, upload_dir=client.uploads, trade_group=client.group,
                            filename="after-repair.png", content_type="image/png", raw=b"new")
    conn.close()
    assert meta["original_name"] == "after-repair.png"
    assert stored_path(client.uploads, meta["stored_name"]).read_bytes() == b"new"


def test_init_db_on_a_pre_existing_database_adds_the_table(client):
    """The migration shape used by this tree: idempotent DDL, rows survive."""
    db = client.db
    conn = sqlite3.connect(db)
    conn.execute("DROP TABLE trade_attachments")
    conn.commit()
    conn.close()

    import database
    database.DB_PATH = db
    database.init_db()          # run twice: it must be a no-op the second time
    database.init_db()

    conn = sqlite3.connect(db)
    names = [r[0] for r in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")]
    conn.close()
    assert "trade_attachments" in names


def test_list_is_ordered_oldest_first(client):
    ids = [upload(client, name=f"{i}.png", content=bytes([i + 65])).json()["id"]
           for i in range(3)]
    got = [a["id"] for a in
           client.get(f"/api/trades/{client.group}/attachments").json()["attachments"]]
    assert sorted(got) == ids


def test_display_name_is_printable_for_pasted_or_odd_names(client):
    meta = upload(client, name="my\nreport\u0000.pdf", content=b"%PDF", ctype="application/pdf").json()
    name = meta["original_name"]
    assert "\n" not in name and "\x00" not in name
    assert "/" not in name and "\\" not in name
    assert name.endswith(".pdf")
